language: android
jdk: openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/google-cloud-sdk/

env:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - make set-licenses
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
    fi
  - echo $GCLOUD_KEY > gcloud_key.json
  - gcloud auth activate-service-account --key-file gcloud_key.json

install:
  - gcloud components update
  - gcloud config set project example-bb31f

android:
  components:
    - android-27
    - build-tools-27.0.3
    - tools
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

script:
  - make build-ci

after_success:
  - make sonar
