language: android
jdk: openjdk8
sudo: false

env:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
  components:
    - android-27
    - build-tools-27.0.3
    - tools
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

before_install:
  - openssl aes-256-cbc -K $encrypted_cb141303541b_key -iv $encrypted_cb141303541b_iv -in ./tools/gae/credentials.tar.gz.enc -out credentials.tar.gz -d
  - sudo apt-get install google-cloud-sdk
  - tar -xzf credentials.tar.gz
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file client-secret.json
  - yes | sdkmanager "platforms;android-27"
  - make set-licenses
  - mkdir -p app/ && touch app/google-services.json
  - echo $GOOGLE_SERVICES_JSON >> app/google-services.json

install:
  - gcloud config set project $FIREBASE_PROJECT

script:
  - make build-ci

after_success:
  - make sonar
  - ./gradlew coveralls
