language: android
jdk: openjdk8
sudo: false

env:
  global:
    - ADB_INSTALL_TIMEOUT=5
    - PATH=$PATH:$TRAVIS_BUILD_DIR/google-cloud-sdk/bin

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-22
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    - addon-google_apis-google-22
    - sys-img-armeabi-v7a-android-22

before_install:
  - openssl aes-256-cbc -K $encrypted_cb141303541b_key -iv $encrypted_cb141303541b_iv -in ./tools/gae/credentials.tar.gz.enc -out credentials.tar.gz -d
  - openssl aes-256-cbc -K $encrypted_fa08cc4ca265_key -iv $encrypted_fa08cc4ca265_iv -in ./app/distribution/release.keystore.enc -out ./app/distribution/release.keystore -d
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-127.0.0-linux-x86_64.tar.gz
  - tar xf google-cloud-sdk-127.0.0-linux-x86_64.tar.gz
  - echo "y" | ./google-cloud-sdk/bin/gcloud components update beta
  - tar -xzf credentials.tar.gz
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file client-secret.json
  - yes | sdkmanager "platforms;android-27"
  - make set-licenses
  - mkdir -p app/ && touch app/google-services.json
  - echo $GOOGLE_SERVICES_JSON >> app/google-services.json
  - echo $PLAYSTORE_ACCOUNT_JSON >> app/distribution/key.json
  - bundle install
  - bundle update

install:
  - gcloud config set project $FIREBASE_PROJECT

before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -netfast -netdelay none -no-boot-anim -no-snapshot-save -no-snapshot-update-time -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - make build-ci
  - ./google-cloud-sdk/bin/gcloud beta test android run --async --type instrumentation --app ./app/build/output/apk/app-debug.apk --device model=Nexus6,version=21,locale=en,orientation=portrait --device model=Nexus7,version=19,locale=en,orientation=landscape
  - make static-check
  - make combined-coverage

after_success:
  - make sonar
  - make upload-data-coveralls

deploy:
  provider: script
  script: fastlane playstore
  skip_cleanup: true
  on:
    branch: master
