language: android
jdk: openjdk8
sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/google-cloud-sdk/

env:
  - GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - if [ ! -d "${GAE_PYTHONPATH}" ]; then
      python scripts/fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}");
    fi

  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
    fi

  - echo $GCLOUD_KEY > $HOME/gcloud_key.json
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file $HOME/gcloud_key.json

  - make set-licenses

install:
  - gcloud config set project example-bb31f
  - gcloud -q components update gae-python

android:
  components:
    - android-27
    - build-tools-27.0.3
    - tools
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

script:
  - make build-ci

after_success:
  - make sonar
