language: android

sudo: true

jdk: openjdk8

os:
  - linux

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
  components:
    - android-27
    - build-tools-27.0.1
    - tools
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support
    - extra-google-google_play_services

script:
  - echo y && android update sdk --all --no-ui --filter extra-android-m2repository
  - ./gradlew clean build --info
